name: Node-First-work-flow

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
      - run: npm install && npm run test:ci
      
      # - run: cd helloworld && npm install && npm run test:ci

# name: tests-auth

# on:
#   pull_request:
#     paths:
#       - 'helloworld/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: cd helloworld && npm install && npm run test:ci
